---
- name: Update apt cache
  apt: update_cache=yes cache_valid_time=3600
  sudo: yes

- name: Install required software
  apt: name={{ item }} state=present
  sudo: yes
  with_items:
    - mysql-server
    - python-mysqldb

- name: Create mysql database
  mysql_db:
    name={{ task_mysql_db }}
    state=present
  sudo: yes

- name: Create mysql user
  mysql_user: 
    name={{ task_mysql_user }} 
    password={{ task_mysql_password }} 
    priv=*.*:ALL
    host="%"
  sudo: yes

# Creating table in {{ task_mysql_db }}
- name: copy_mysql_table
  copy:
    src: ../files/task_table.sql
    dest: /tmp/task_table.sql
    owner: root
    group: root
    mode: 0644

- name: Create mysql table
  mysql_db:
    name={{ task_mysql_db }}
    state=import
    target=/tmp/task_table.sql

# Coping config file and callig for hendler which will restart the service
- name: copy_mysql_config
  copy:
    src: ../files/my.cnf
    dest: /etc/mysql/my.cnf
    owner: root
    group: root
    mode: 0644
  notify: restart mysql
# tasks file for mysql
